// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcp_service.proto

/*
Package imrpc is a generated protocol buffer package.

It is generated from these files:
	tcp_service.proto

It has these top-level messages:
	Request
	ReqSendMsg
	Response
*/
package tcpprotol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_REQ_HEART_BEAT RequestType = 0
	RequestType_REQ_SEND_MSG   RequestType = 1
)

var RequestType_name = map[int32]string{
	0: "REQ_HEART_BEAT",
	1: "REQ_SEND_MSG",
}
var RequestType_value = map[string]int32{
	"REQ_HEART_BEAT": 0,
	"REQ_SEND_MSG":   1,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResponseType int32

const (
	ResponseType_RES_SEND_MSG ResponseType = 0
)

var ResponseType_name = map[int32]string{
	0: "RES_SEND_MSG",
}
var ResponseType_value = map[string]int32{
	"RES_SEND_MSG": 0,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}
func (ResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Request struct {
	Type  RequestType `protobuf:"varint,1,opt,name=type,enum=imrpc.RequestType" json:"type,omitempty"`
	Datas string      `protobuf:"bytes,2,opt,name=datas" json:"datas,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetType() RequestType {
	if m != nil {
		return m.Type
	}
	return RequestType_REQ_HEART_BEAT
}

func (m *Request) GetDatas() string {
	if m != nil {
		return m.Datas
	}
	return ""
}

type ReqSendMsg struct {
}

func (m *ReqSendMsg) Reset()                    { *m = ReqSendMsg{} }
func (m *ReqSendMsg) String() string            { return proto.CompactTextString(m) }
func (*ReqSendMsg) ProtoMessage()               {}
func (*ReqSendMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Response struct {
	Type  ResponseType `protobuf:"varint,1,opt,name=type,enum=imrpc.ResponseType" json:"type,omitempty"`
	Code  int32        `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Datas string       `protobuf:"bytes,3,opt,name=datas" json:"datas,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetType() ResponseType {
	if m != nil {
		return m.Type
	}
	return ResponseType_RES_SEND_MSG
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetDatas() string {
	if m != nil {
		return m.Datas
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "imrpc.Request")
	proto.RegisterType((*ReqSendMsg)(nil), "imrpc.ReqSendMsg")
	proto.RegisterType((*Response)(nil), "imrpc.Response")
	proto.RegisterEnum("imrpc.RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("imrpc.ResponseType", ResponseType_name, ResponseType_value)
}

func init() { proto.RegisterFile("tcp_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0xa9, 0x82, 0xc8, 0xd8, 0x60, 0x1d, 0x3d, 0xa0, 0xa7, 0xa6, 0x07, 0x25, 0x1c, 0x6a,
	0x02, 0x37, 0x6f, 0x14, 0x1b, 0xf4, 0x00, 0xc1, 0x6d, 0xaf, 0xa6, 0xa9, 0xdb, 0xd1, 0x6c, 0x62,
	0xbb, 0x4b, 0x77, 0x35, 0xe9, 0xbf, 0x37, 0xb4, 0x46, 0x8a, 0xb7, 0xdd, 0x79, 0x2f, 0xdf, 0x9b,
	0x79, 0x70, 0x61, 0xb8, 0x4a, 0x34, 0x95, 0xdf, 0x82, 0x93, 0xaf, 0x4a, 0x69, 0x24, 0xf6, 0x44,
	0x5e, 0x2a, 0xee, 0x2d, 0xa1, 0xcf, 0x68, 0xfb, 0x45, 0xda, 0xe0, 0x2d, 0x74, 0x4d, 0xa5, 0x68,
	0x64, 0xb9, 0xd6, 0x78, 0x38, 0x45, 0xbf, 0x36, 0xf8, 0xbf, 0x6a, 0x5c, 0x29, 0x62, 0xb5, 0x8e,
	0x57, 0xd0, 0xcb, 0x52, 0x93, 0xea, 0xd1, 0x91, 0x6b, 0x8d, 0x07, 0xac, 0xf9, 0x78, 0x36, 0x00,
	0xa3, 0x6d, 0x44, 0x45, 0xb6, 0xd2, 0x1f, 0xde, 0x2b, 0x9c, 0x32, 0xd2, 0x4a, 0x16, 0x9a, 0xf0,
	0xee, 0x80, 0x7b, 0xf9, 0xc7, 0x6d, 0xe4, 0x16, 0x18, 0xa1, 0xcb, 0x65, 0x46, 0x35, 0xb7, 0xc7,
	0xea, 0xf7, 0x3e, 0xec, 0xb8, 0x15, 0x36, 0x99, 0xc1, 0x59, 0x6b, 0x2f, 0x44, 0x18, 0xb2, 0xf0,
	0x25, 0x79, 0x0a, 0xe7, 0x2c, 0x4e, 0x82, 0x70, 0x1e, 0x3b, 0x1d, 0x74, 0xc0, 0xde, 0xcd, 0xa2,
	0x70, 0xfd, 0x98, 0xac, 0xa2, 0xa5, 0x63, 0x4d, 0x5c, 0xb0, 0xdb, 0xa1, 0x8d, 0x23, 0xda, 0x3b,
	0x3a, 0xd3, 0x07, 0xe8, 0x2f, 0x64, 0x9e, 0xa7, 0x45, 0x86, 0xf7, 0x60, 0xaf, 0xa5, 0x11, 0xef,
	0xd5, 0xe2, 0x53, 0x50, 0x61, 0x70, 0x78, 0x58, 0xc7, 0xcd, 0xf9, 0xbf, 0x33, 0x82, 0x6b, 0x18,
	0x08, 0xe9, 0x8b, 0xdc, 0x2f, 0x15, 0x0f, 0xe0, 0x39, 0x67, 0x8a, 0x6f, 0x76, 0x45, 0x6f, 0xac,
	0xb7, 0x93, 0xba, 0xf1, 0xd9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x53, 0x85, 0x03, 0x86,
	0x01, 0x00, 0x00,
}
